print("\t\t\tUSER INFORMATION")
name = input("Enter your name : ")
age = input("Enter your age : ")
dob = input("Enter your dob : ")
phone = input("Enter your phone number : ")
gender = input("Enter your gender : ")
qualification = input("Enter your qualification : ")
address = input("Enter your address : ")
salary = input("Enter your salary : ")
state = input("Enter your state : ")
country = input("Enter your country : ")
print("\n")
print("\t\t\tDETAILS")
print(f"name = {name}")
print(f"age = {age}")
print(f"dob = {dob}")
print(f"phone number = {phone}")
print(f"gender = {gender}")
print(f"qualification = {qualification}")
print(f"address = {address}")
print(f"salary = {salary}")
print(f"state = {state}")
print(f"country = {country}")